### ISSUE TITLE
Use PathogenTrack when a sample has multiple pairs of fastq files

### ISSUE THREAD

**Issue by JohnWang1997** [ncrna/PathogenTrack#1]
Appreciations for your wonderful job in "PathogenTrack and Yeskit: tools for identifying intracellular pathogens from single-cell RNA-sequencing datasets as illustrated by application to COVID-19" !

I noticed that the input of PathogenTrack (count) includes a pair of fastq files (read1 and read2). I wonder how should I use PathogenTrack when a sample has multiple pairs of fastq files? 

For example, Sample01_S1_L001_R1_001.fastq.gz, Sample01_S1_L001_R2_001.fastq.gz, Sample01_S1_L002_R1_001.fastq.gz, Sample01_S1_L002_R2_001.fastq.gz.

Best wishes

**Comment by ncrna** [comment]
Thank you for your interest in using PathogenTrack! When there are more fastq files, I suggest that you merge them together using cat command, for example, cat Input_01_1.fastq.gz Input_02_1.fastq.gz > Input_merged_1.fastq.gz; then cat Input_01_2.fastq.gz Input_02_2.fastq.gz > Input_merged_2.fastq.gz. Finally, use the merged fastq files instead. Hope it would help.

Cheers,

Wei Zhang
