### ISSUE TITLE
Getting empty microbes.tsv file

### ISSUE THREAD

**Issue by AIProd** [ncrna/PathogenTrack#2]
After running the code for about 8 hours, I am getting empty microbes.tsv file with just barcodes in it, no counts. Any idea as to how we can resolve this, please
![image](https://user-images.githubusercontent.com/69484036/185089869-1020a832-f1b8-4bc4-9a6a-caf18aff1092.png)
.

**Comment by ncrna** [comment]
Sorry for the late reply. When you get an empty microbes.tsv, try to find the microbe of interest in microbes.fa, if the microbe of interest is not present in microbes.fa, it probably means you don't have a microbe in your single-cell RNA-seq data. If the microbe of interest is present in the microbes.fa, try setting the parameter "--min_reads 1". Good luck.
