### ISSUE TITLE
About how to track cov19

### ISSUE THREAD

**Issue by juychen** [ncrna/PathogenTrack#4]
Hi, 

In your paper, I saw that you have analysis on virus.
But this part is missing in the tutorial to run virus detection?
Are there any option that we can switch to call virus?

Regards,
Junyi

**Comment by ncrna** [comment]
Thank you for your interest in using PathogenTrack! PathogenTrack will detect bacteria, virus, and fungi in default mode, and in the output matrix, each row represents a microbe species, you can track virus by the row names. Hope it would help!

Wei Zhang

**Comment by juychen** [comment]
Hi, I would like to know how to interpret the report. 
What are the numbers in each of the columns? 
For example, 442374 is the number of reads or UMI counts?

 89.06	442374	442374	U	0	unclassified
 10.94	54356	745	R	1	root
 10.79	53601	3766	R1	131567	  cellular organisms
 10.03	49833	0	D	2759	    Eukaryota
 10.03	49833	0	D1	33154	      Opisthokonta
 10.03	49833	0	K	33208	        Metazoa
 10.03	49833	0	K1	6072	          Eumetazoa
 10.03	49833	0	K2	33213	            Bilateria
 10.03	49833	0	K3	33511	              Deuterostomia
 10.03	49833	0	P	7711	                Chordata
 10.03	49833	0	P1	89593	                  Craniata
 10.03	49833	0	P2	7742	                    Vertebrata
 10.03	49833	0	P3	7776	                      Gnathostomata
 10.03	49833	0	P4	117570	                        Teleostomi
 10.03	49833	0	P5	117571	                          Euteleostomi
 10.03	49833	0	P6	8287	                            Sarcopterygii
 10.03	49833	0	P7	1338369	                              Dipnotetrapodomorpha
 10.03	49833	0	P8	32523	                                Tetrapoda
 10.03	49833	0	P9	32524	                                  Amniota
 10.03	49833	0	C	40674	                                    Mammalia
 10.03	49833	0	C1	32525	                                      Theria
 10.03	49833	0	C2	9347	                                        Eutheria
 10.03	49833	0	C3	1437010	                                          Boreoeutheria
 10.03	49833	0	C4	314146	                                            Euarchontoglires
 10.03	49833	0	O	9443	                                              Primates
 10.03	49833	0	O1	376913	                                                Haplorrhini
 10.03	49833	0	O2	314293	                                                  Simiiformes
 10.03	49833	0	O3	9526	                                                    Catarrhini
 10.03	49833	0	O4	314295	                                                      Hominoidea
 10.03	49833	0	F	9604	                                                        Hominidae
 10.03	49833	0	F1	207598	                                                          Homininae
 10.03	49833	0	G	9605	                                                            Homo
 10.03	49833	49833	S	9606	                                                              Homo sapiens

**Comment by ncrna** [comment]
From the attached report, "442374" is the number of reads that classified by kraken2. In the final step, PathogenTrack will deduplicate the reads into UMI counts. Hope it would help!
