### ISSUE TITLE
mutiple read1 and read2 for  PathogenTrack count

### ISSUE THREAD

**Issue by zhuhonglin2022** [ncrna/PathogenTrack#5]
Dear PathogenTrack team,
Thanks for your excellent work,
I installed your package and it ran smoothly with your test data.
However, when I used my own data, the Fastq files for read1 and read2 are multiple as below, all the reads belong to one sample HC1. What can I do with my data?
I am very appreciative of your help.

HC1-1_S1_L003_R1_001.fastq.gz  HC1-5_S1_L003_R1_001.fastq.gz
HC1-1_S1_L003_R2_001.fastq.gz  HC1-5_S1_L003_R2_001.fastq.gz
HC1-2_S1_L003_R1_001.fastq.gz  HC1-6_S1_L003_R1_001.fastq.gz
HC1-2_S1_L003_R2_001.fastq.gz  HC1-6_S1_L003_R2_001.fastq.gz
HC1-3_S1_L003_R1_001.fastq.gz  HC1-7_S1_L003_R1_001.fastq.gz
HC1-3_S1_L003_R2_001.fastq.gz  HC1-7_S1_L003_R2_001.fastq.gz
HC1-4_S1_L003_R1_001.fastq.gz  HC1-8_S1_L003_R1_001.fastq.gz
HC1-4_S1_L003_R2_001.fastq.gz  HC1-8_S1_L003_R2_001.fastq.gz

**Comment by ncrna** [comment]
Thank you for using PathogenTrack. You can combine these fastq files as follows:

cat HC1-1_S1_L003_R1_001.fastq.gz HC1-2_S1_L003_R1_001.fastq.gz HC1-3_S1_L003_R1_001.fastq.gz ... HC1-8_S1_L003_R1_001.fastq.gz > HC1-8_S9_L003_R1_001.fastq.gz

cat HC1-1_S1_L003_R2_001.fastq.gz HC1-2_S1_L003_R2_001.fastq.gz HC1-3_S1_L003_R2_001.fastq.gz ... HC1-8_S1_L003_R2_001.fastq.gz > HC1-8_S9_L003_R2_001.fastq.gz

Tips: 1. Use 'cat' command to cat all Read1 to a single file, eg., HC1-8_S9_L003_R1_001.fastq.gz
         2. The order for Read1 and Read2 should be the same. eg., cat HC1-1, HC1-2, HC1-3, HC1-4...,HC1-8 > HC1-9
Hope it helps. Good luck!

**Comment by zhuhonglin2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Dear Zhang,
        Thank you so much!Best,Honglin
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                honglinzhu
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/17/2023 10:04，Wei ***@***.***> wrote： 



Thank you for using PathogenTrack. You can combine these fastq files as follows:
cat HC1-1_S1_L003_R1_001.fastq.gz HC1-2_S1_L003_R1_001.fastq.gz HC1-3_S1_L003_R1_001.fastq.gz ... HC1-8_S1_L003_R1_001.fastq.gz > HC1-8_S9_L003_R1_001.fastq.gz
cat HC1-1_S1_L003_R2_001.fastq.gz HC1-2_S1_L003_R2_001.fastq.gz HC1-3_S1_L003_R2_001.fastq.gz ... HC1-8_S1_L003_R2_001.fastq.gz > HC1-8_S9_L003_R2_001.fastq.gz
Tips: 1. Use 'cat' command to cat all Read1 to a single file, eg., HC1-8_S9_L003_R1_001.fastq.gz
2. The order for Read1 and Read2 should be the same. eg., cat HC1-1, HC1-2, HC1-3, HC1-4...,HC1-8 > HC1-9
Hope it helps. Good luck!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
