### ISSUE TITLE
Use with 5' RNA-seq

### ISSUE THREAD

**Issue by JaneChik** [ncrna/PathogenTrack#7]
Hello! It was nice to discover your tool. I was wondering if it is possible to use it on 5' RNA-seq data. What adjustments should be done if you think it is possible ?

Thank you!

**Comment by ncrna** [comment]
Sorry for the late reply! Thank you for your interest on PathogenTrack! It is possible to use PathogenTrack on 5' scRNA-seq data with no adjustments. Hope it would help.

Wei Zhang

**Comment by JaneChik** [comment]
Thank you for the reply!
